### ISSUE TITLE
Customizable meta in settings.

### ISSUE THREAD

**Issue by r-kjha** [ControlPanel-gg/docs#4]
![Screenshot_20210808_162842](https://user-images.githubusercontent.com/87710356/128629445-de62ec08-79e2-4595-a8f9-7fdedaf2069b.jpg)
![USER_SCOPED_TEMP_DATA_orca-image--1562719941](https://user-images.githubusercontent.com/87710356/128629491-4537bf79-bc87-4320-adf8-4204a693250c.jpeg)
Meta fields in settings that will allow to create a customizable embed when a url is shared on other websites like discord or facebook.

**Comment by AVMG20** [comment]
wrong repo
