### ISSUE TITLE
New Payment Gateway - Request

### ISSUE THREAD

**Issue by Abraar69** [ControlPanel-gg/docs#76]
What about making an Payment Gateway for PayU? Since I can't use Stripe..
https://www.payu.in/

**Comment by 1day2die** [comment]
Please use the format provided to create a new Suggestion/Issue

![image](https://user-images.githubusercontent.com/8725848/178278746-2e6f4bf8-fd0a-47ae-a0c3-b8fbda7500e4.png)

**Comment by Abraar69** [comment]
> Please use the format provided to create a new Suggestion/Issue
> 
> ![image](https://user-images.githubusercontent.com/8725848/178278746-2e6f4bf8-fd0a-47ae-a0c3-b8fbda7500e4.png)
> 
> Edit: Also, please go to the main repository.
> This repo is for the docs only xD

I need to fix my eyes, thanks once again
